sonar.projectKey=williamrobin15_security-scanning
sonar.organization=williamrobin15
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.app.json
