name: Angular CI/CD

# 1. Triggers (Kab chalega?)
on:
  push:
    branches: [ "main" ] # Jab bhi 'main' branch pe push hoga
  pull_request:
    branches: [ "main" ] # Jab koi Pull Request 'main' me merge hone aayegi

# 2. Jobs (Kya kaam karega?)
jobs:
  build:
    # Konsa OS use karein? (Ubuntu sabse fast aur common hai)
    runs-on: ubuntu-latest

    steps:
    # Step 1: Code ko virtual machine par le kar aao
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Gitleaks Scan
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: --verbose --redact

    # Step: Trivy SCA Scan (Software Composition Analysis)
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs' # Filesystem scan
        scan-ref: '.' # Poora project scan karo
        format: 'table'
        exit-code: '1' # Agar vulnerability mile to pipeline FAIL kar do
        severity: 'CRITICAL,HIGH' # Sirf Critical aur High par fail hoga

    
    # Step 2: Node.js setup karo (Angular ke liye zaroori hai)
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm' # Purani files cache karega taaki next time fast ho

    # Step 3: Library files install karo
    - name: Install Dependencies
      run: npm install

    # Step 4: Code ko compile/build karo
    - name: Build Project
      run: npm run build
